# -*- coding: utf-8 -*-
"""Task_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R79h7XYIv0fYrPKpqBn3rTGgA-N2602s
"""

!pip3 install gitpython

!pip install JPype1

import os
os.mkdir("/content/git_repos")

import pandas as pd
import git
from git.repo.base import Repo

git_repos="/content/git_repos/"

link = 'https://github.com/sarangkashalkar/VectorAI_Proj/'

from glob import glob

files = []
start_dir = "/content/git_repos"
pattern   = "*.pb"

for dir,_,_ in os.walk(start_dir):
    files.extend(glob(os.path.join(dir,pattern))) 

    compile_java(files)

import os.path, subprocess
from subprocess
import STDOUT, PIPE

def compile_model(files):
   subprocess.check_call(['.pb', files])

def execute_model(files, stdin):
   model_path, ext = os.path.splitext(files)

cmd = [
   '-classpath', '/content/model_path()',
   'model_name'
]
proc = subprocess.Popen(cmd, stdin = PIPE, stdout = PIPE, stderr = STDOUT)
stdout, stderr = proc.communicate(stdin)

compile_model('sender.py')
execute_model('receiver.py', 'model_name.pb')











